- name: Déployer l'application sur Kubernetes
  hosts: localhost
  tasks:
    - name: Appliquer les configurations Kubernetes
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'deploymentservice.yaml') }}"
